### ISSUE TITLE
Pogo Modifications based only on labels

### ISSUE THREAD

**Issue by ypriverol** [cschlaffner/PoGo#1]
@cschlaffner 

We are now exporting the data from PRIDE using Pogo. The way you are handling right now the PTMs is complex because we need to map all the PSI-Mod Identifiers into Pogo Notations. Would be great to encapsulate in ( ) the identifier of the modification and not the name. Any idea?

**Comment by ypriverol** [comment]
@cschlaffner @gPirkes @cns89 We have started to work with pogo. Something important is that with PTMs it can not handle the Nterm and CTerm modifications. We found the only handle this: 
 
 S(phospho)NNNNACM(oxidation) 

How we should handle the modifications in the N and C-terminal. ?

**Comment by cschlaffner** [comment]
@ypriverol 
For the PSI identifiers I would like to understand your requirement a bit more in detail. Currently PoGo only allows the following PSI names as modifications and colour codes them:
phospho, acetyl, amidated, oxidation, methyl, glygly, sulfo, palmitoyl, formyl, demaidated.
As for the PSI identifiers would they need to be colour coded in the *_ptm.bed output? 

With regards to N and C-terminal modifications. I have found that these pose an issue with visualising as separate entities. PTMs in PoGo are associated with an amino acid and therefore with the underlying codon (3 bp). I could update PoGo to include N and C-terminal modifications as modifications of single base pairs at the N anc C-termini of peptides to incorporate these and provide a visual aid to show these modifications are at the termini of the peptide. I am happy for input regarding the visualisation and incorporation of these types of modifications in PoGo

**Comment by ypriverol** [comment]
@cschlaffner 
>For the PSI identifiers I would like to understand your requirement a bit more in detail. Currently PoGo only allows the following PSI names as modifications and colour codes them:
phospho, acetyl, amidated, oxidation, methyl, glygly, sulfo, palmitoyl, formyl, demaidated.
As for the PSI identifiers would they need to be colour coded in the *_ptm.bed output?

We have some others biologically relevant modifications we would like to have a color for them. I will add here the list today. In the same line, Can you let me know which tool are you using to visualize the PTMS in the Genome Coordinates? Also to see other like spectral count Features. ?

Can this annotations be seen in browsers such as ENSEMBL or UCSC?  

>With regards to N and C-terminal modifications. I have found that these pose an issue with visualising as separate entities. PTMs in PoGo are associated with an amino acid and therefore with the underlying codon (3 bp). I could update PoGo to include N and C-terminal modifications as modifications of single base pairs at the N anc C-termini of peptides to incorporate these and provide a visual aid to show these modifications are at the termini of the peptide. I am happy for input regarding the visualisation and incorporation of these types of modifications in PoGo.

This is extremelly important because we have a lot of modifications in the N and C-terminal that we dont want to loss. But is not high priority.

**Comment by cschlaffner** [comment]
@ypriverol 
Thanks. I will incorporate your list with colour code into the code.
PTM visualisation is provided by the *_ptm.bed file. This can be loaded in UCSC/ENSEMBL/IGV and others and can also be included in trackhubs.
Spectral counts are only provided in the *.gtf output as separate tags. GTF files can be loaded in ENSEMBL, UCSC, and IGV. 
The quantitative information provided in the "Quant" column in the input file is used for the *.GCT output format. This file can only be loaded in IGV (https://github.com/igvteam/igv). 

I will include the N anc C-terminal modifications as soon as possible over the coming weeks.

**Comment by ypriverol** [comment]
Then: 

- The bed file contains the unmodified sequences. 
- The _ptm.bed the modified peptides with the corresponding color coding. 
- The *.GTF files the spectral counts. and the GCT the Quant data. 

Can you normally upload multiple files into the same view in any of these browsers?

**Comment by ypriverol** [comment]
@cschlaffner I have been continue doing testing. When I upload the ptm.bed into ENSEMBL browser Asembly GRCh38 this is the error I'm receiving. Is this normal? 

![screen shot 2017-06-26 at 13 20 10](https://user-images.githubusercontent.com/52113/27538966-6973da74-5a72-11e7-9586-292e708374f5.png)

**Comment by ypriverol** [comment]
@cschlaffner GCT file format is internal file format on your side or is the standard file format. One of our GCT files is 47GB. Is that normal?

**Comment by cschlaffner** [comment]
@ypriverol 
Multiple files can be visualized inUCSC, ENSEMBL and IGV to show the different aspects as you pointed out in the list for file types. However, they can only be loaded one file at a time.

The error message in Ensembl, that the file does not evaluate as a valid BED file is not normal. Can you maybe give access to the file for me to have a quick look at the issue?

GCT files are basically matrices of samples (columns) and peptides (rows) with cells indicating the quantitation. Generally, GCT files are larger than BED files. How many peptides are you mapping for how many samples? I have not come across a 47GB GCT file. The largest file I have generated so far was for mapping 230k peptides across 69 tissues resulting in a 53MB GCT file.

**Comment by ypriverol** [comment]
@cschlaffner  
   If the data do not have Quant information, We expect to do not pass any Quant Column. We are 
   exporting a column with Quant = 0 for all the peptides but is generating this massive GCT file that we 
   don't need. Who can we avoid this?

**Comment by cschlaffner** [comment]
By default PoGo generates all output formats. If you only want specific formats, e.g. just *.bed and *_ptm.bed please use the parameter "-format" ["PoGo -fasta ... -gtf ... -in ... -format BED,PTMBED"]. This setting will not generate GFT nor GCT file. To include GTF files please use "-format BED,PTMBED,GTF".

**Comment by ypriverol** [comment]
@cschlaffner  thanks.

**Comment by ypriverol** [comment]
I will close this issue and split them into other multiple ones.
