### ISSUE TITLE
Pogo Issue in Human wrong mapping to chromosome 2b

### ISSUE THREAD

**Issue by ypriverol** [cschlaffner/PoGo#11]
@cschlaffner 
We have a problem with the current version of the pogo. I just added the following file with the current version of pride cluster peptides. When the mapping finish some of the peptides are the map to `chromosome 2b`, What is the reason of that if this chromosome is not in my input. The ENSEMBL browser does not check for that but if I add the chr option to the bed and load into UCSC it will complain.  

Here the input. 
[pride_cluster_peptides_9606_Human.pogo.zip](https://github.com/cschlaffner/PoGo/files/1296138/pride_cluster_peptides_9606_Human.pogo.zip)

**Comment by cschlaffner** [comment]
This issue has been resolved with the latest commit.

**Comment by ypriverol** [comment]
Hi @cschlaffer thanks for fixing the error. I have added the chr option to the tool. Do you know if the bed files based on ensembl fasta/gtf files is ucsc now compliant? Are the differences with the 0 or 1 based standard affecting us?
