### ISSUE TITLE
Support the mismatch in the name  

### ISSUE THREAD

**Issue by ypriverol** [cschlaffner/PoGo#12]
Right now the output file is missing in pogo, the current version of Pogo uses the file name of the input as a prefix for all the output files. However, most of the users will run the same tool allowing 1 or 2 mismatches to do the research. I will suggest that we include in the name of the output file the number of mismatches like `_MM1` or `_MM2`. This will allow running the multiple analysis in the same input file.

**Comment by cschlaffner** [comment]
The latest commit now supports this. File names are marked with "_1MM", "_2MM-(1in5)", and "_2MM" when PoGo options for 1 mismatch, 2 mismatches (1 in 5), or 2 mismatches selected for execution, respectively.

**Comment by ypriverol** [comment]
Thanks @cschlaffner for implementing this.
