### ISSUE TITLE
-mm not producing any result files

### ISSUE THREAD

**Issue by mbdebian** [cschlaffner/PoGo#15]
Hi, I was trying PoGo '-mm' parameter with values '1' and '2' for a sample project, before we move on to implementing extra tracks with gaps in the trackhub-creator, but it produces no output files.

I've run it for Mouse taxonomy.

I may be missing something ^_^

Any ideas?

Thanks guys,
Manuel

**Comment by ypriverol** [comment]
@mbdebian can you share the original file that you use for doing this?

**Comment by mbdebian** [comment]
It's on our LSF, on HipChat you'll find the path to that project.

**Comment by ypriverol** [comment]
Thanks @mbdebian, @cschlaffner I will take this issue.

**Comment by mbdebian** [comment]
We just run PoGo for a project, and it produced the following file results:
PXD001110-9606.pogo_1MM.bed
PXD001110-9606.pogo_1MM.gct
PXD001110-9606.pogo_1MM_no-ptm.bed
PXD001110-9606.pogo_1MM_out.gtf
PXD001110-9606.pogo_1MM_patch_hapl_scaff.bed
PXD001110-9606.pogo_1MM_patch_hapl_scaff.gct
PXD001110-9606.pogo_1MM_patch_hapl_scaff_no-ptm.bed
PXD001110-9606.pogo_1MM_patch_hapl_scaff_out.gtf
PXD001110-9606.pogo_1MM_patch_hapl_scaff_ptm.bed
PXD001110-9606.pogo_1MM_ptm.bed
PXD001110-9606.pogo_unmapped.txt

Would it be possible to have the 'unmapped' file matching the same pattern? e.g. PXD001110-9606.pogo_1MM_unmapped.txt
