### ISSUE TITLE
Pogo an species

### ISSUE THREAD

**Issue by ypriverol** [cschlaffner/PoGo#3]
@cschlaffner as we discuss Pogo should work for other species in apart of Human. For us High priority is Mouse, but the all these species are now available from cluster. 

https://github.com/PRIDE-Cluster/cluster-file-exporter/blob/master/src/main/resources/prop/species_metadata.conf

This is high - high priority for us.

**Comment by cschlaffner** [comment]
@ypriverol as discussed today here are the 25 species that PoGo will support

<table>
<tr><th>Common name</th><th>Scientific name</th><th>Taxon ID</th></tr>
<tr><td>C.intestinalis</td><td>Ciona intestinalis</td><td>7719</td></tr>
<tr><td>Cat</td><td>Felis catus</td><td>9685</td></tr>
<tr><td>Chicken</td><td>Gallus gallus</td><td>9031</td></tr>
<tr><td>Chimpanzee</td><td>Pan troglodytes</td><td>9598</td></tr>
<tr><td>Cow</td><td>Bos taurus</td><td>9913</td></tr>
<tr><td>Dog</td><td>Canis lupus familiaris</td><td>9615</td></tr>
<tr><td>Gorilla</td><td>Gorilla gorilla gorilla</td><td>9595</td></tr>
<tr><td>Horse</td><td>Equus caballus</td><td>9796</td></tr>
<tr><td>Human</td><td>Homo sapiens</td><td>9606</td></tr>
<tr><td>Macaque</td><td>Macaca mulatta</td><td>9544</td></tr>
<tr><td>Marmoset</td><td>Callithrix jacchus</td><td>9483</td></tr>
<tr><td>Medaka</td><td>Oryzias latipes</td><td>8090</td></tr>
<tr><td>Mouse</td><td>Mus musculus</td><td>10090</td></tr>
<tr><td>Olive baboon</td><td>Papio anubis</td><td>9555</td></tr>
<tr><td>Opossum</td><td>Monodelphis domestica</td><td>13616</td></tr>
<tr><td>Orangutan</td><td>Pongo abelii</td><td>9601</td></tr>
<tr><td>Pig</td><td>Sus scrofa</td><td>9823</td></tr>
<tr><td>Platypus</td><td>Ornithorhynchus anatinus</td><td>9258</td></tr>
<tr><td>Rabbit</td><td>Oryctolagus cuniculus</td><td>9986</td></tr>
<tr><td>Rat</td><td>Rattus norvegicus</td><td>10116</td></tr>
<tr><td>Sheep</td><td>Ovis aries</td><td>9940</td></tr>
<tr><td>Tetraodon</td><td>Tetraodon nigroviridis</td><td>99883</td></tr>
<tr><td>Turkey</td><td>Meleagris gallopavo</td><td>9103</td></tr>
<tr><td>Vervet-AGM</td><td>Chlorocebus sabaeus</td><td>60711</td></tr>
<tr><td>Zebra Finch</td><td>Taeniopygia guttata</td><td>59729</td></tr>
</table>

**Comment by ypriverol** [comment]
@cschlaffner this is excellent news. Thanks for all your work, do we have any bacteria (Prokaryotes)? or  Arabidopsis thaliana.

**Comment by cschlaffner** [comment]
Not yet. I will try and come up with a different way to deal with chromosome names and gene/transcript identifiers over the next few weeks. This will, hopefully, then allow mapping for bacteria and other species.

**Comment by ypriverol** [comment]
thanks if you want you can do the PR and I can Review the code and accept the PR.

**Comment by cschlaffner** [comment]
#9 
@ypriverol PR done. Would be great if you could review the code and accept the PR, thanks.

**Comment by cschlaffner** [comment]
@ypriverol as requested taxonomy IDs are now included in PR #9  as valid options for species selection.
