### ISSUE TITLE
Pogo Peptides output devided on three main sets 

### ISSUE THREAD

**Issue by ypriverol** [cschlaffner/PoGo#4]
@cschlaffner The pogo outputs should be devided in three main tracks:
   - ptm.bed Modified peptides wich contains all the modified peptides including the colors and for
     the peptides with modifications but not biologically relevant, then it should be black color and 
     only the sequences + UNMOD IDs. 
   - all.bed All petides should included in this track: Modified and un-Modified peptides. 
   - non_ptm.bed all non-modified peptides variants.

**Comment by cschlaffner** [comment]
Has been added. Peptides without PTMs are returned in the *_no-ptm.bed output file. They are marked through grey colour.
